---
swagger: "2.0"
info:
  description: "Rainbond open api"
  version: "v1"
  title: "Rainbond Open API"
  termsOfService: "https://cloud.goodrain.com"
  contact:
    email: "barnett@goodrain.com"
  license:
    name: "LGPL License"
host: "cloud.goodrain.com"
basePath: "/"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
security:
- Bearer: []
paths:
  /openapi/v1/teams:
    get:
      tags:
      - "openapi-team"
      description: "获取用户所在团队列表"
      operationId: "openapi_v1_teams_list"
      parameters:
      - name: "query"
        in: "query"
        description: "团队名称搜索"
        required: false
        type: "string"
        x-exportParamName: "Query"
        x-optionalDataType: "String"
      - name: "page"
        in: "query"
        description: "页码"
        required: false
        type: "string"
        x-exportParamName: "Page"
        x-optionalDataType: "String"
      - name: "page_size"
        in: "query"
        description: "每页数量"
        required: false
        type: "string"
        x-exportParamName: "PageSize"
        x-optionalDataType: "String"
      responses:
        "200":
          schema:
            $ref: "#/definitions/ListTeamResp"
    post:
      tags:
      - "openapi-team"
      description: "add team"
      operationId: "openapi_v1_teams_create"
      parameters:
      - in: "body"
        name: "data"
        required: true
        schema:
          $ref: "#/definitions/CreateTeamReq"
        x-exportParamName: "Data"
      responses:
        "201":
          schema:
            $ref: "#/definitions/TeamBaseInfo"
  /openapi/v1/teams/{team_id}/certificates:
    get:
      tags:
      - "openapi-team"
      description: "获取团队下证书列表"
      operationId: "openapi_v1_teams_certificates_list"
      parameters:
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      - name: "page"
        in: "query"
        description: "页码"
        required: false
        type: "number"
        x-exportParamName: "Page"
        x-optionalDataType: "Float32"
      - name: "page_size"
        in: "query"
        description: "每页数量"
        required: false
        type: "number"
        x-exportParamName: "PageSize"
        x-optionalDataType: "Float32"
      responses:
        "200":
          schema:
            $ref: "#/definitions/TeamCertificatesL"
    post:
      tags:
      - "openapi-team"
      description: "添加证书"
      operationId: "openapi_v1_teams_certificates_create"
      parameters:
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      - in: "body"
        name: "data"
        required: true
        schema:
          $ref: "#/definitions/TeamCertificatesC"
        x-exportParamName: "Data"
      responses:
        "200":
          schema:
            $ref: "#/definitions/TeamCertificatesR"
  /openapi/v1/teams/{team_id}/certificates/{certificate_id}:
    get:
      tags:
      - "openapi-team"
      description: "获取团队下证书列表"
      operationId: "openapi_v1_teams_certificates_read"
      parameters:
      - name: "certificate_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "CertificateId"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      responses:
        "200":
          schema:
            $ref: "#/definitions/TeamCertificatesR"
    put:
      tags:
      - "openapi-team"
      description: "更新证书"
      operationId: "openapi_v1_teams_certificates_update"
      parameters:
      - name: "certificate_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "CertificateId"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      - in: "body"
        name: "data"
        required: true
        schema:
          $ref: "#/definitions/TeamCertificatesC"
        x-exportParamName: "Data"
      responses:
        "200":
          schema:
            $ref: "#/definitions/TeamCertificatesR"
    delete:
      tags:
      - "openapi-team"
      description: "删除证书"
      operationId: "openapi_v1_teams_certificates_delete"
      parameters:
      - name: "certificate_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "CertificateId"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      responses: {}
  /openapi/v1/teams/{team_id}/regions/{region_name}/apps:
    get:
      tags:
      - "openapi-apps"
      description: "团队应用列表"
      operationId: "openapi_v1_teams_regions_apps_list"
      parameters:
      - name: "region_name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "RegionName"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      - name: "query"
        in: "query"
        description: "搜索查询应用名称，团队名称"
        required: false
        type: "string"
        x-exportParamName: "Query"
        x-optionalDataType: "String"
      responses:
        "200":
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AppBaseInfo"
    post:
      tags:
      - "openapi-apps"
      description: "创建应用"
      operationId: "openapi_v1_teams_regions_apps_create"
      parameters:
      - name: "region_name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "RegionName"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      - in: "body"
        name: "data"
        required: true
        schema:
          $ref: "#/definitions/AppPostInfo"
        x-exportParamName: "Data"
      responses:
        "200":
          schema:
            $ref: "#/definitions/AppBaseInfo"
  /openapi/v1/teams/{team_id}/regions/{region_name}/apps/{app_id}:
    get:
      tags:
      - "openapi-apps"
      description: "应用详情"
      operationId: "openapi_v1_teams_regions_apps_read"
      parameters:
      - name: "app_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      - name: "region_name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "RegionName"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      responses:
        "200":
          schema:
            $ref: "#/definitions/AppInfo"
  /openapi/v1/teams/{team_id}/regions/{region_name}/apps/{app_id}/copy:
    get:
      tags:
      - "openapi-apps"
      description: "获取需要复制的应用组件信息"
      operationId: "openapi_v1_teams_regions_apps_copy_list"
      parameters:
      - name: "app_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      - name: "region_name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "RegionName"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      responses:
        "200":
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AppCopyL"
    post:
      tags:
      - "openapi-apps"
      description: "复制应用"
      operationId: "openapi_v1_teams_regions_apps_copy_create"
      parameters:
      - name: "app_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      - name: "region_name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "RegionName"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      - in: "body"
        name: "data"
        required: true
        schema:
          $ref: "#/definitions/AppCopyC"
        x-exportParamName: "Data"
      responses:
        "200":
          schema:
            $ref: "#/definitions/AppCopyCRes"
  /openapi/v1/teams/{team_id}/regions/{region_name}/apps/{app_id}/httpdomains:
    get:
      tags:
      - "openapi-gateway"
      description: "获取应用http访问策略列表"
      operationId: "openapi_v1_teams_regions_apps_httpdomains_list"
      parameters:
      - name: "app_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      - name: "region_name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "RegionName"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      responses:
        "200":
          schema:
            type: "array"
            items:
              $ref: "#/definitions/HTTPGatewayRule"
    post:
      tags:
      - "openapi-apps"
      description: "创建HTTP网关策略"
      operationId: "openapi_v1_teams_regions_apps_httpdomains_create"
      parameters:
      - name: "app_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      - name: "region_name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "RegionName"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      - in: "body"
        name: "data"
        required: true
        schema:
          $ref: "#/definitions/PostHTTPGatewayRule"
        x-exportParamName: "Data"
      responses:
        "200":
          schema:
            $ref: "#/definitions/HTTPGatewayRule"
  /openapi/v1/teams/{team_id}/regions/{region_name}/apps/{app_id}/operations:
    post:
      tags:
      - "openapi-apps"
      description: "操作应用"
      operationId: "openapi_v1_teams_regions_apps_operations_create"
      parameters:
      - name: "app_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      - name: "region_name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "RegionName"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      - in: "body"
        name: "data"
        required: true
        schema:
          $ref: "#/definitions/ServiceGroupOperations"
        x-exportParamName: "Data"
      responses:
        "200":
          schema:
            $ref: "#/definitions/Success"
        "400":
          schema:
            $ref: "#/definitions/Fail"
        "404":
          schema:
            $ref: "#/definitions/Fail"
  /openapi/v1/teams/{team_id}/regions/{region_name}/apps/{app_id}/services:
    get:
      tags:
      - "openapi-apps"
      description: "查询应用下组件列表"
      operationId: "openapi_v1_teams_regions_apps_services_list"
      parameters:
      - name: "app_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      - name: "region_name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "RegionName"
      - name: "team_id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "TeamId"
      responses:
        "200":
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceBaseInfo"
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  AppBaseInfo:
    type: "object"
    required:
    - "group_name"
    - "region_name"
    - "tenant_id"
    properties:
      ID:
        type: "integer"
        title: "ID"
        readOnly: true
      group_name:
        type: "string"
        description: "组名"
        title: "Group name"
        minLength: 1
        maxLength: 128
      is_default:
        type: "boolean"
        description: "默认组件"
        title: "Is default"
      note:
        type: "string"
        description: "备注"
        title: "Note"
        maxLength: 2048
        x-nullable: true
      order_index:
        type: "integer"
        description: "应用排序"
        title: "Order index"
        minimum: -2147483648
        maximum: 2147483647
      region_name:
        type: "string"
        description: "区域中心名称"
        title: "Region name"
        minLength: 1
        maxLength: 64
      tenant_id:
        type: "string"
        description: "租户id"
        title: "Tenant id"
        minLength: 1
        maxLength: 32
    example:
      tenant_id: "tenant_id"
      note: "note"
      group_name: "group_name"
      region_name: "region_name"
      ID: 0
      is_default: true
      order_index: 441289069
  AppCopyC:
    type: "object"
    required:
    - "services"
    - "target_app_id"
    - "target_region_name"
    - "target_team_name"
    properties:
      services:
        type: "array"
        items:
          $ref: "#/definitions/AppCopyModify"
      target_app_id:
        type: "integer"
        description: "应用id"
        title: "Target app id"
      target_region_name:
        type: "string"
        description: "数据中心名称"
        title: "Target region name"
        minLength: 1
        maxLength: 32
      target_team_name:
        type: "string"
        description: "团队名称"
        title: "Target team name"
        minLength: 1
        maxLength: 32
    example:
      target_region_name: "target_region_name"
      target_app_id: 0
      services:
      - change: "change"
        service_id: "service_id"
      - change: "change"
        service_id: "service_id"
      target_team_name: "target_team_name"
  AppCopyCRes:
    type: "object"
    required:
    - "services"
    properties:
      services:
        type: "array"
        items:
          $ref: "#/definitions/ServiceBaseInfo"
    example:
      services:
      - service_region: "service_region"
        tenant_id: "tenant_id"
        service_key: "service_key"
        extend_method: "不伸缩"
        service_alias: "service_alias"
        min_memory: 413233370
        check_event_id: "check_event_id"
        service_cname: "service_cname"
        check_uuid: "check_uuid"
        expired_time: "2000-01-23T04:56:07.000+00:00"
        language: "language"
        is_service: true
        open_webhooks: true
        is_upgrate: true
        update_time: "2000-01-23T04:56:07.000+00:00"
        total_memory: 1847456234
        min_cpu: -1517921766
        code_version: "code_version"
        oauth_service_id: -1158723813
        service_id: "service_id"
        git_url: "git_url"
        image: "image"
        docker_cmd: "docker_cmd"
        service_source: "service_source"
        create_time: "2000-01-23T04:56:07.000+00:00"
        git_project_id: 441289069
        service_origin: "service_origin"
        tenant_service_group_id: 885365090
        update_version: -594390510
        version: "version"
        build_upgrade: true
        code_from: "code_from"
        service_type: "service_type"
        creater: -1803530559
        create_status: "create_status"
        cmd: "cmd"
        category: "category"
        min_node: 273751188
        desc: "desc"
        server_type: "server_type"
        status: "status"
      - service_region: "service_region"
        tenant_id: "tenant_id"
        service_key: "service_key"
        extend_method: "不伸缩"
        service_alias: "service_alias"
        min_memory: 413233370
        check_event_id: "check_event_id"
        service_cname: "service_cname"
        check_uuid: "check_uuid"
        expired_time: "2000-01-23T04:56:07.000+00:00"
        language: "language"
        is_service: true
        open_webhooks: true
        is_upgrate: true
        update_time: "2000-01-23T04:56:07.000+00:00"
        total_memory: 1847456234
        min_cpu: -1517921766
        code_version: "code_version"
        oauth_service_id: -1158723813
        service_id: "service_id"
        git_url: "git_url"
        image: "image"
        docker_cmd: "docker_cmd"
        service_source: "service_source"
        create_time: "2000-01-23T04:56:07.000+00:00"
        git_project_id: 441289069
        service_origin: "service_origin"
        tenant_service_group_id: 885365090
        update_version: -594390510
        version: "version"
        build_upgrade: true
        code_from: "code_from"
        service_type: "service_type"
        creater: -1803530559
        create_status: "create_status"
        cmd: "cmd"
        category: "category"
        min_node: 273751188
        desc: "desc"
        server_type: "server_type"
        status: "status"
  AppCopyL:
    type: "object"
    required:
    - "app_name"
    - "create_status"
    - "deploy_version"
    - "min_memory"
    - "service_alias"
    - "service_cname"
    - "service_id"
    - "service_type"
    - "update_time"
    - "version"
    properties:
      app_name:
        type: "string"
        description: "应用名称"
        title: "App name"
        minLength: 1
        maxLength: 64
      build_source:
        type: "string"
        title: "Build source"
        readOnly: true
      create_status:
        type: "string"
        description: "创建状态"
        title: "Create status"
        minLength: 1
        maxLength: 32
      deploy_version:
        type: "string"
        description: "构建版本"
        title: "Deploy version"
        minLength: 1
        maxLength: 32
      min_memory:
        type: "string"
        description: "组件运行内存"
        title: "Min memory"
        minLength: 1
        maxLength: 32
      service_alias:
        type: "string"
        description: "组件昵称"
        title: "Service alias"
        minLength: 1
        maxLength: 64
      service_cname:
        type: "string"
        description: "组件中文名称"
        title: "Service cname"
        minLength: 1
        maxLength: 128
      service_id:
        type: "string"
        description: "id"
        title: "Service id"
        minLength: 1
        maxLength: 32
      service_type:
        type: "string"
        description: "组件类型"
        title: "Service type"
        minLength: 1
        maxLength: 64
      update_time:
        type: "string"
        format: "date-time"
        description: "更新日期"
        title: "Update time"
      version:
        type: "string"
        description: "版本"
        title: "Version"
        minLength: 1
        maxLength: 32
    example:
      app_name: "app_name"
      service_type: "service_type"
      update_time: "2000-01-23T04:56:07.000+00:00"
      service_alias: "service_alias"
      min_memory: "min_memory"
      service_cname: "service_cname"
      build_source: "build_source"
      service_id: "service_id"
      create_status: "create_status"
      deploy_version: "deploy_version"
      version: "version"
  AppCopyModify:
    type: "object"
    required:
    - "service_id"
    properties:
      change:
        type: "string"
        title: "Change"
        readOnly: true
      service_id:
        type: "string"
        description: "id"
        title: "Service id"
        minLength: 1
        maxLength: 32
    example:
      change: "change"
      service_id: "service_id"
  AppInfo:
    type: "object"
    required:
    - "app_id"
    - "enterprise_id"
    - "group_name"
    - "region_name"
    - "running_service_count"
    - "service_count"
    - "status"
    - "team_name"
    - "tenant_id"
    - "used_cpu"
    - "used_momory"
    properties:
      ID:
        type: "integer"
        title: "ID"
        readOnly: true
      app_id:
        type: "integer"
        description: "应用id"
        title: "App id"
      enterprise_id:
        type: "string"
        description: "企业ID(联合云ID)"
        title: "Enterprise id"
        minLength: 1
        maxLength: 32
      group_name:
        type: "string"
        description: "组名"
        title: "Group name"
        minLength: 1
        maxLength: 128
      is_default:
        type: "boolean"
        description: "默认组件"
        title: "Is default"
      note:
        type: "string"
        description: "备注"
        title: "Note"
        maxLength: 2048
        x-nullable: true
      order_index:
        type: "integer"
        description: "应用排序"
        title: "Order index"
        minimum: -2147483648
        maximum: 2147483647
      region_name:
        type: "string"
        description: "区域中心名称"
        title: "Region name"
        minLength: 1
        maxLength: 64
      running_service_count:
        type: "integer"
        description: "正在运行的组件数量"
        title: "Running service count"
      service_count:
        type: "integer"
        description: "组件数量"
        title: "Service count"
      status:
        type: "string"
        description: "应用状态"
        title: "Status"
        enum:
        - "running"
        - "part_running"
        - "closed"
      team_name:
        type: "string"
        description: "团队名"
        title: "Team name"
        minLength: 1
        maxLength: 32
      tenant_id:
        type: "string"
        description: "租户id"
        title: "Tenant id"
        minLength: 1
        maxLength: 32
      used_cpu:
        type: "integer"
        description: "分配的cpu"
        title: "Used cpu"
      used_momory:
        type: "integer"
        description: "分配的内存"
        title: "Used momory"
    example:
      tenant_id: "tenant_id"
      note: "note"
      group_name: "group_name"
      service_count: 5
      enterprise_id: "enterprise_id"
      is_default: true
      order_index: -1517921766
      running_service_count: 5
      team_name: "team_name"
      used_momory: 7
      region_name: "region_name"
      ID: 0
      used_cpu: 2
      app_id: 6
      status: "running"
  AppPostInfo:
    type: "object"
    required:
    - "app_name"
    properties:
      app_name:
        type: "string"
        description: "应用名称"
        title: "App name"
        minLength: 1
        maxLength: 128
      app_note:
        type: "string"
        description: "应用备注"
        title: "App note"
        maxLength: 2048
        default: ""
    example:
      app_name: "app_name"
      app_note: "app_note"
  CertificatesR:
    type: "object"
    required:
    - "alias"
    - "certificate_type"
    - "end_data"
    - "has_expired"
    - "id"
    - "issued_by"
    - "issued_to"
    properties:
      alias:
        type: "string"
        description: "证书名称"
        title: "Alias"
        minLength: 1
        maxLength: 64
      certificate_type:
        type: "string"
        description: "证书类型"
        title: "Certificate type"
        minLength: 1
        maxLength: 32
      end_data:
        type: "string"
        format: "date-time"
        description: "过期时间"
        title: "End data"
      has_expired:
        type: "boolean"
        description: "是否过期"
        title: "Has expired"
      id:
        type: "integer"
        description: "id"
        title: "Id"
      issued_by:
        type: "string"
        description: "证书来源"
        title: "Issued by"
        minLength: 1
        maxLength: 32
      issued_to:
        type: "array"
        description: "域名列表"
        items:
          type: "string"
    example:
      has_expired: true
      issued_by: "issued_by"
      issued_to:
      - "issued_to"
      - "issued_to"
      alias: "alias"
      id: 0
      certificate_type: "certificate_type"
      end_data: "2000-01-23T04:56:07.000+00:00"
  CreateTeamReq:
    type: "object"
    required:
    - "enterprise_id"
    - "tenant_name"
    properties:
      creater:
        type: "integer"
        description: "团队所属人，未提供时默认使用登录用户作为所属人"
        title: "Creater"
      enterprise_id:
        type: "string"
        description: "团队所属企业ID,未提供时默认使用请求用户企业ID"
        title: "Enterprise id"
        minLength: 1
        maxLength: 32
      region:
        type: "string"
        description: "默认开通的数据中心，未指定则不开通"
        title: "Region"
        minLength: 1
        maxLength: 24
      tenant_name:
        type: "string"
        description: "团队名称"
        title: "Tenant name"
        minLength: 1
        maxLength: 24
    example:
      tenant_name: "tenant_name"
      creater: 0
      enterprise_id: "enterprise_id"
      region: "region"
  Fail:
    type: "object"
    required:
    - "msg"
    properties:
      msg:
        type: "string"
        title: "Msg"
        minLength: 1
        maxLength: 300
  HTTPGatewayRule:
    type: "object"
    required:
    - "domain_name"
    - "http_rule_id"
    - "region_id"
    - "service_id"
    - "service_name"
    - "tenant_id"
    properties:
      ID:
        type: "integer"
        title: "ID"
        readOnly: true
      certificate_id:
        type: "integer"
        description: "证书ID"
        title: "Certificate id"
        minimum: -2147483648
        maximum: 2147483647
      container_port:
        type: "integer"
        description: "容器端口"
        title: "Container port"
        minimum: -2147483648
        maximum: 2147483647
      create_time:
        type: "string"
        format: "date-time"
        description: "创建时间"
        title: "Create time"
        readOnly: true
      domain_cookie:
        type: "string"
        description: "域名cookie"
        title: "Domain cookie"
      domain_heander:
        type: "string"
        description: "域名heander"
        title: "Domain heander"
      domain_name:
        type: "string"
        description: "域名"
        title: "Domain name"
        minLength: 1
        maxLength: 128
      domain_path:
        type: "string"
        description: "域名path"
        title: "Domain path"
      domain_type:
        type: "string"
        description: "组件域名类型"
        title: "Domain type"
        minLength: 1
        maxLength: 20
      http_rule_id:
        type: "string"
        description: "http_rule_id"
        title: "Http rule id"
        minLength: 1
        maxLength: 128
      is_outer_service:
        type: "boolean"
        description: "是否已开启对外端口"
        title: "Is outer service"
      is_senior:
        type: "boolean"
        description: "是否有高级路由"
        title: "Is senior"
      protocol:
        type: "string"
        description: "域名类型 http https httptphttps httpandhttps"
        title: "Protocol"
        minLength: 1
        maxLength: 15
      region_id:
        type: "string"
        description: "region id"
        title: "Region id"
        minLength: 1
        maxLength: 36
      rule_extensions:
        type: "string"
        description: "扩展功能"
        title: "Rule extensions"
      service_alias:
        type: "string"
        description: "组件别名"
        title: "Service alias"
        minLength: 1
        maxLength: 64
      service_id:
        type: "string"
        description: "组件id"
        title: "Service id"
        minLength: 1
        maxLength: 32
      service_name:
        type: "string"
        description: "组件名"
        title: "Service name"
        minLength: 1
        maxLength: 64
      tenant_id:
        type: "string"
        description: "租户id"
        title: "Tenant id"
        minLength: 1
        maxLength: 32
      the_weight:
        type: "integer"
        description: "权重"
        title: "The weight"
        minimum: -2147483648
        maximum: 2147483647
      type:
        type: "integer"
        description: "类型（默认：0， 自定义：1）"
        title: "Type"
        minimum: -2147483648
        maximum: 2147483647
    example:
      tenant_id: "tenant_id"
      container_port: -1517921766
      domain_type: "domain_type"
      rule_extensions: "rule_extensions"
      service_alias: "service_alias"
      create_time: "2000-01-23T04:56:07.000+00:00"
      http_rule_id: "http_rule_id"
      is_outer_service: true
      service_name: "service_name"
      region_id: "region_id"
      the_weight: 413233370
      domain_heander: "domain_heander"
      type: 273751188
      is_senior: true
      certificate_id: 441289069
      domain_name: "domain_name"
      protocol: "protocol"
      domain_cookie: "domain_cookie"
      domain_path: "domain_path"
      service_id: "service_id"
      ID: 0
  ListTeamResp:
    type: "object"
    required:
    - "tenants"
    properties:
      tenants:
        type: "array"
        items:
          $ref: "#/definitions/TeamInfo"
      total:
        type: "integer"
        title: "Total"
    example:
      tenants:
      - role_infos:
        - role_name: "role_name"
          role_id: 6
        - role_name: "role_name"
          role_id: 6
        tenant_id: "tenant_id"
        tenant_name: "tenant_name"
        is_active: true
        create_time: "2000-01-23T04:56:07.000+00:00"
        creater: "creater"
        service_num: 1
        region_num: 0
        tenant_alias: "tenant_alias"
        enterprise_id: "enterprise_id"
      - role_infos:
        - role_name: "role_name"
          role_id: 6
        - role_name: "role_name"
          role_id: 6
        tenant_id: "tenant_id"
        tenant_name: "tenant_name"
        is_active: true
        create_time: "2000-01-23T04:56:07.000+00:00"
        creater: "creater"
        service_num: 1
        region_num: 0
        tenant_alias: "tenant_alias"
        enterprise_id: "enterprise_id"
      total: 5
  PostHTTPGatewayRule:
    type: "object"
    required:
    - "container_port"
    - "domain_name"
    - "service_id"
    properties:
      certificate_id:
        type: "integer"
        description: "证书id"
        title: "Certificate id"
      container_port:
        type: "integer"
        description: "绑定端口"
        title: "Container port"
      domain_cookie:
        type: "string"
        description: "域名cookie"
        title: "Domain cookie"
        minLength: 1
      domain_header:
        type: "string"
        description: "域名header"
        title: "Domain header"
        minLength: 1
      domain_name:
        type: "string"
        description: "域名"
        title: "Domain name"
        minLength: 1
        maxLength: 253
      domain_path:
        type: "string"
        description: "域名路径"
        title: "Domain path"
        minLength: 1
        default: "/"
      rule_extensions:
        type: "array"
        description: "规则扩展"
        items:
          type: "string"
      service_id:
        type: "string"
        description: "应用组件id"
        title: "Service id"
        minLength: 1
      the_weight:
        type: "integer"
        title: "The weight"
      whether_open:
        type: "boolean"
        description: "是否开放"
        title: "Whether open"
        default: false
  RoleInfo:
    type: "object"
    required:
    - "role_id"
    - "role_name"
    properties:
      role_id:
        type: "integer"
        description: "角色ID"
        title: "Role id"
      role_name:
        type: "string"
        description: "角色名称"
        title: "Role name"
        minLength: 1
        maxLength: 32
    description: "用户在团队中拥有的角色"
    example:
      role_name: "role_name"
      role_id: 6
  ServiceBaseInfo:
    type: "object"
    required:
    - "category"
    - "image"
    - "service_alias"
    - "service_id"
    - "service_key"
    - "service_region"
    - "status"
    - "tenant_id"
    - "version"
    properties:
      build_upgrade:
        type: "boolean"
        description: "组件构建后是否升级"
        title: "Build upgrade"
      category:
        type: "string"
        description: "组件分类：application,cache,store"
        title: "Category"
        minLength: 1
        maxLength: 15
      check_event_id:
        type: "string"
        description: "组件检测事件ID"
        title: "Check event id"
        maxLength: 32
        x-nullable: true
      check_uuid:
        type: "string"
        description: "组件检测ID"
        title: "Check uuid"
        maxLength: 36
        x-nullable: true
      cmd:
        type: "string"
        description: "启动参数"
        title: "Cmd"
        maxLength: 2048
        x-nullable: true
      code_from:
        type: "string"
        description: "代码来源:gitlab,github"
        title: "Code from"
        maxLength: 20
        x-nullable: true
      code_version:
        type: "string"
        description: "代码版本"
        title: "Code version"
        maxLength: 100
        x-nullable: true
      create_status:
        type: "string"
        description: "组件创建状态 creating|complete"
        title: "Create status"
        maxLength: 15
        x-nullable: true
      create_time:
        type: "string"
        format: "date-time"
        description: "创建时间"
        title: "Create time"
        readOnly: true
      creater:
        type: "integer"
        description: "组件创建者"
        title: "Creater"
        minimum: -2147483648
        maximum: 2147483647
      desc:
        type: "string"
        description: "描述"
        title: "Desc"
        maxLength: 200
        x-nullable: true
      docker_cmd:
        type: "string"
        description: "镜像创建命令"
        title: "Docker cmd"
        maxLength: 1024
        x-nullable: true
      expired_time:
        type: "string"
        format: "date-time"
        description: "过期时间"
        title: "Expired time"
        x-nullable: true
      extend_method:
        type: "string"
        description: "组件部署类型,stateless or state"
        title: "Extend method"
        enum:
        - "不伸缩"
        - "垂直伸缩"
      git_project_id:
        type: "integer"
        description: "gitlab 中项目id"
        title: "Git project id"
        minimum: -2147483648
        maximum: 2147483647
      git_url:
        type: "string"
        description: "code代码仓库"
        title: "Git url"
        maxLength: 2047
        x-nullable: true
      image:
        type: "string"
        description: "镜像"
        title: "Image"
        minLength: 1
        maxLength: 200
      is_service:
        type: "boolean"
        description: "是否inner组件"
        title: "Is service"
      is_upgrate:
        type: "boolean"
        description: "是否可以更新"
        title: "Is upgrate"
      language:
        type: "string"
        description: "代码语言"
        title: "Language"
        maxLength: 40
        x-nullable: true
      min_cpu:
        type: "integer"
        description: "cpu个数"
        title: "Min cpu"
        minimum: -2147483648
        maximum: 2147483647
      min_memory:
        type: "integer"
        description: "内存大小单位（M）"
        title: "Min memory"
        minimum: -2147483648
        maximum: 2147483647
      min_node:
        type: "integer"
        description: "启动个数"
        title: "Min node"
        minimum: -2147483648
        maximum: 2147483647
      oauth_service_id:
        type: "integer"
        description: "拉取源码所用的OAuth服务id"
        title: "Oauth service id"
        minimum: -2147483648
        maximum: 2147483647
        x-nullable: true
      open_webhooks:
        type: "boolean"
        description: "是否开启自动触发部署功能（兼容老版本组件）"
        title: "Open webhooks"
      server_type:
        type: "string"
        description: "源码仓库类型"
        title: "Server type"
        minLength: 1
        maxLength: 5
      service_alias:
        type: "string"
        description: "组件别名"
        title: "Service alias"
        minLength: 1
        maxLength: 100
      service_cname:
        type: "string"
        description: "组件名"
        title: "Service cname"
        minLength: 1
        maxLength: 100
      service_id:
        type: "string"
        description: "组件id"
        title: "Service id"
        minLength: 1
        maxLength: 32
      service_key:
        type: "string"
        description: "组件key"
        title: "Service key"
        minLength: 1
        maxLength: 32
      service_origin:
        type: "string"
        description: "组件创建类型cloud云市组件,assistant云帮组件"
        title: "Service origin"
        minLength: 1
        maxLength: 15
      service_region:
        type: "string"
        description: "组件所属区"
        title: "Service region"
        minLength: 1
        maxLength: 64
      service_source:
        type: "string"
        description: "组件来源(source_code, market, docker_run, docker_compose)"
        title: "Service source"
        maxLength: 15
        x-nullable: true
      service_type:
        type: "string"
        description: "组件类型:web,mysql,redis,mongodb,phpadmin"
        title: "Service type"
        maxLength: 50
        x-nullable: true
      status:
        type: "string"
        description: "组件状态"
        title: "Status"
        minLength: 1
        maxLength: 32
      tenant_id:
        type: "string"
        description: "租户id"
        title: "Tenant id"
        minLength: 1
        maxLength: 32
      tenant_service_group_id:
        type: "integer"
        description: "组件归属的组件组id"
        title: "Tenant service group id"
        minimum: -2147483648
        maximum: 2147483647
      total_memory:
        type: "integer"
        description: "内存使用M"
        title: "Total memory"
        minimum: -2147483648
        maximum: 2147483647
      update_time:
        type: "string"
        format: "date-time"
        description: "更新时间"
        title: "Update time"
        readOnly: true
      update_version:
        type: "integer"
        description: "内部发布次数"
        title: "Update version"
        minimum: -2147483648
        maximum: 2147483647
      version:
        type: "string"
        description: "版本"
        title: "Version"
        minLength: 1
        maxLength: 255
    example:
      service_region: "service_region"
      tenant_id: "tenant_id"
      service_key: "service_key"
      extend_method: "不伸缩"
      service_alias: "service_alias"
      min_memory: 413233370
      check_event_id: "check_event_id"
      service_cname: "service_cname"
      check_uuid: "check_uuid"
      expired_time: "2000-01-23T04:56:07.000+00:00"
      language: "language"
      is_service: true
      open_webhooks: true
      is_upgrate: true
      update_time: "2000-01-23T04:56:07.000+00:00"
      total_memory: 1847456234
      min_cpu: -1517921766
      code_version: "code_version"
      oauth_service_id: -1158723813
      service_id: "service_id"
      git_url: "git_url"
      image: "image"
      docker_cmd: "docker_cmd"
      service_source: "service_source"
      create_time: "2000-01-23T04:56:07.000+00:00"
      git_project_id: 441289069
      service_origin: "service_origin"
      tenant_service_group_id: 885365090
      update_version: -594390510
      version: "version"
      build_upgrade: true
      code_from: "code_from"
      service_type: "service_type"
      creater: -1803530559
      create_status: "create_status"
      cmd: "cmd"
      category: "category"
      min_node: 273751188
      desc: "desc"
      server_type: "server_type"
      status: "status"
  ServiceGroupOperations:
    type: "object"
    required:
    - "action"
    properties:
      action:
        type: "string"
        description: "操作类型"
        title: "Action"
        enum:
        - "stop"
        - "start"
        - "upgrade"
        - "deploy"
      service_ids:
        type: "array"
        description: "组件ID列表，不传值则操作应用下所有组件"
        items:
          type: "string"
    example:
      action: "stop"
      service_ids:
      - "service_ids"
      - "service_ids"
  Success:
    type: "object"
    required:
    - "msg"
    properties:
      msg:
        type: "string"
        title: "Msg"
        minLength: 1
        maxLength: 300
    example:
      msg: "msg"
  TeamBaseInfo:
    type: "object"
    required:
    - "tenant_name"
    properties:
      ID:
        type: "integer"
        title: "ID"
        readOnly: true
      create_time:
        type: "string"
        format: "date-time"
        description: "创建时间"
        title: "Create time"
        readOnly: true
      creater:
        type: "integer"
        description: "租户创建者"
        title: "Creater"
        minimum: -2147483648
        maximum: 2147483647
      enterprise_id:
        type: "string"
        description: "企业id"
        title: "Enterprise id"
        maxLength: 32
        x-nullable: true
      expired_time:
        type: "string"
        format: "date-time"
        description: "过期时间"
        title: "Expired time"
        x-nullable: true
      is_active:
        type: "boolean"
        description: "激活状态"
        title: "Is active"
      limit_memory:
        type: "integer"
        description: "内存大小单位（M）"
        title: "Limit memory"
        minimum: -2147483648
        maximum: 2147483647
      region:
        type: "string"
        description: "区域中心,弃用"
        title: "Region"
        minLength: 1
        maxLength: 30
      tenant_alias:
        type: "string"
        description: "团队别名"
        title: "Tenant alias"
        maxLength: 64
        x-nullable: true
      tenant_id:
        type: "string"
        description: "租户id"
        title: "Tenant id"
        minLength: 1
        maxLength: 33
      tenant_name:
        type: "string"
        description: "租户名称"
        title: "Tenant name"
        minLength: 1
        maxLength: 64
      update_time:
        type: "string"
        format: "date-time"
        description: "更新时间"
        title: "Update time"
        readOnly: true
    example:
      tenant_id: "tenant_id"
      tenant_name: "tenant_name"
      update_time: "2000-01-23T04:56:07.000+00:00"
      is_active: true
      create_time: "2000-01-23T04:56:07.000+00:00"
      limit_memory: -1517921766
      creater: 441289069
      expired_time: "2000-01-23T04:56:07.000+00:00"
      ID: 0
      tenant_alias: "tenant_alias"
      enterprise_id: "enterprise_id"
      region: "region"
  TeamCertificatesC:
    type: "object"
    required:
    - "alias"
    - "certificate"
    - "certificate_type"
    - "private_key"
    properties:
      alias:
        type: "string"
        description: "证书名称"
        title: "Alias"
        minLength: 1
        maxLength: 64
      certificate:
        type: "string"
        description: "证书key"
        title: "Certificate"
        minLength: 1
        maxLength: 8192
      certificate_type:
        type: "string"
        description: "证书类型"
        title: "Certificate type"
        minLength: 1
        maxLength: 32
      private_key:
        type: "string"
        description: "证书"
        title: "Private key"
        minLength: 1
        maxLength: 8192
    example:
      certificate: "certificate"
      alias: "alias"
      private_key: "private_key"
      certificate_type: "certificate_type"
  TeamCertificatesL:
    type: "object"
    required:
    - "list"
    - "page"
    - "page_size"
    - "total"
    properties:
      list:
        type: "array"
        items:
          $ref: "#/definitions/CertificatesR"
      page:
        type: "integer"
        title: "Page"
      page_size:
        type: "integer"
        title: "Page size"
      total:
        type: "integer"
        title: "Total"
    example:
      total: 5
      page: 6
      list:
      - has_expired: true
        issued_by: "issued_by"
        issued_to:
        - "issued_to"
        - "issued_to"
        alias: "alias"
        id: 0
        certificate_type: "certificate_type"
        end_data: "2000-01-23T04:56:07.000+00:00"
      - has_expired: true
        issued_by: "issued_by"
        issued_to:
        - "issued_to"
        - "issued_to"
        alias: "alias"
        id: 0
        certificate_type: "certificate_type"
        end_data: "2000-01-23T04:56:07.000+00:00"
      page_size: 1
  TeamCertificatesR:
    type: "object"
    required:
    - "alias"
    - "certificate"
    - "certificate_type"
    - "id"
    - "private_key"
    properties:
      alias:
        type: "string"
        description: "证书名称"
        title: "Alias"
        minLength: 1
        maxLength: 64
      certificate:
        type: "string"
        description: "证书key"
        title: "Certificate"
        minLength: 1
        maxLength: 8192
      certificate_type:
        type: "string"
        description: "证书类型"
        title: "Certificate type"
        minLength: 1
        maxLength: 32
      id:
        type: "integer"
        description: "id"
        title: "Id"
      private_key:
        type: "string"
        description: "证书"
        title: "Private key"
        minLength: 1
        maxLength: 8192
    example:
      certificate: "certificate"
      alias: "alias"
      private_key: "private_key"
      id: 0
      certificate_type: "certificate_type"
  TeamInfo:
    type: "object"
    required:
    - "enterprise_id"
    - "tenant_alias"
    - "tenant_id"
    - "tenant_name"
    properties:
      create_time:
        type: "string"
        format: "date-time"
        description: "创建时间"
        title: "Create time"
      creater:
        type: "string"
        description: "团队拥有者用户"
        title: "Creater"
        minLength: 1
      enterprise_id:
        type: "string"
        description: "企业ID"
        title: "Enterprise id"
        minLength: 1
        maxLength: 32
      is_active:
        type: "boolean"
        description: "是否激活"
        title: "Is active"
      region_num:
        type: "integer"
        description: "团队开通的数据中心数量"
        title: "Region num"
      role_infos:
        type: "array"
        description: "用户在团队中拥有的角色"
        items:
          $ref: "#/definitions/RoleInfo"
      service_num:
        type: "integer"
        description: "团队的组件数量"
        title: "Service num"
      tenant_alias:
        type: "string"
        description: "团队别名"
        title: "Tenant alias"
        minLength: 1
        maxLength: 24
      tenant_id:
        type: "string"
        description: "团队ID"
        title: "Tenant id"
        minLength: 1
        maxLength: 32
      tenant_name:
        type: "string"
        description: "团队名称"
        title: "Tenant name"
        minLength: 1
        maxLength: 24
    example:
      role_infos:
      - role_name: "role_name"
        role_id: 6
      - role_name: "role_name"
        role_id: 6
      tenant_id: "tenant_id"
      tenant_name: "tenant_name"
      is_active: true
      create_time: "2000-01-23T04:56:07.000+00:00"
      creater: "creater"
      service_num: 1
      region_num: 0
      tenant_alias: "tenant_alias"
      enterprise_id: "enterprise_id"
